# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.cache/wt [current_project]
set_property parent.project_path C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/memfile.dat
read_vhdl -library xil_defaultlib {
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_mem_instructions.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_shift_left_by_2.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_datapath.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_top.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_alu.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_adder.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_mem_data.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_decoder_alu.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_decoder_main.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/computer_top.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_controller.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_register_file.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_sign_extender.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/display_hex.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_flip_flop_register.vhd
  C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/sources_1/imports/new/mips_multiplexer_2_input.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/constrs_1/imports/Desktop/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/kjones/Desktop/mips_fpga_nexsys4_ddr/mips.srcs/constrs_1/imports/Desktop/Nexys4DDR_Master.xdc]


synth_design -top computer_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef computer_top.dcp

catch { report_utilization -file computer_top_utilization_synth.rpt -pb computer_top_utilization_synth.pb }
